name: CI/CD Frontend Pipeline

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd FrontEnd
          npm ci

      - name: Check for unused imports
        run: |
          cd FrontEnd
          npx eslint src --ext .js,.jsx,.ts,.tsx

      - name: Build application
        run: |
          cd FrontEnd
          npm run build

      - name: Build Docker image
        run: |
          cd FrontEnd
          docker build -t authorship-attribution-frontend .

      - name: Run tests
        run: |
          cd FrontEnd
          npm test 
