name: CI/CD Frontend Pipeline

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd FrontEnd
          npm ci

      - name: Check for unused imports
        run: |
          cd FrontEnd
          npx eslint src --ext .js,.jsx,.ts,.tsx

      - name: Build application
        run: |
          cd FrontEnd
          npm run build

      - name: Build Docker image
        run: |
          cd FrontEnd
          docker build -t authorship-attribution-frontend .

      - name: Run tests with coverage
        run: |
          cd FrontEnd
          npm test -- --coverage
          mkdir -p coverage && mv coverage/lcov.info coverage/

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.javascript.lcov.reportPaths=FrontEnd/coverage/lcov.info
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}